package com.stationannouncer.mtr;

import com.stationannouncer.StationAnnouncer;
import com.stationannouncer.block.DecorBlock;
import com.stationannouncer.block.ElCeilingBlock;
import com.stationannouncer.block.ElDeckBlock;
import com.stationannouncer.block.ElGirderBlock;
import com.stationannouncer.block.ElLandingRoofBlock;
import com.stationannouncer.block.ElMezzanineFloorBlock;
import com.stationannouncer.block.ElRailingBlock;
import com.stationannouncer.block.ElRoofBlock;
import com.stationannouncer.block.ElRoofLightBlock;
import com.stationannouncer.block.ElStairRoofBlock;
import com.stationannouncer.block.ElStairSideBlock;
import com.stationannouncer.block.ElStairUpperBlock;
import com.stationannouncer.block.ElWallBlock;
import com.stationannouncer.block.ElWallDoorwayBlock;
import com.stationannouncer.block.FacingDecorBlock;
import com.stationannouncer.block.SubwayStairBlock;
import com.stationannouncer.item.EdgeRunItem;
import com.stationannouncer.item.ElStairSideItem;
import com.stationannouncer.item.ElStairUpperItem;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.text.Text;

import java.util.ArrayList;
import java.util.List;

/**
 * The ESI theme of the el station kit: the modern look of the MTA's Enhanced
 * Station Initiative rebuilds (Astoria line, 2018-2020) - charcoal steel, a
 * silver standing-seam roof over a wood soffit, clear glass / black / mesh
 * windscreen bays, L-arm LED lamps, black-and-stainless mezzanines with art
 * glass. Every block is the SAME Java class as its classic el_* counterpart
 * (same placement rules, same connections, same shapes); only the models and
 * textures differ, all generated by tools/gen_esi_theme.py from the classic
 * kit. Kept on their own creative tab.
 */
public final class EsiKit {
    private EsiKit() {
    }

    public static final List<net.minecraft.item.ItemConvertible> ENTRIES = new ArrayList<>();
    /** Every ESI block, for the client's render-layer registration. */
    public static final List<Block> BLOCKS = new ArrayList<>();

    private static AbstractBlock.Settings metal() {
        return AbstractBlock.Settings.create().strength(2.0f, 6.0f).sounds(BlockSoundGroup.METAL).nonOpaque();
    }

    private static AbstractBlock.Settings glass() {
        return AbstractBlock.Settings.create().strength(2.0f, 6.0f).sounds(BlockSoundGroup.GLASS).nonOpaque();
    }

    private static AbstractBlock.Settings structure() {
        return AbstractBlock.Settings.create().strength(3.0f, 6.0f).sounds(BlockSoundGroup.METAL).nonOpaque();
    }

    // platform
    public static final ElRoofBlock ROOF = new ElRoofBlock(metal());
    public static final ColumnBlock POST = new ColumnBlock(metal(), Block.createCuboidShape(6.0, 0.0, 6.0, 10.0, 16.0, 10.0));
    public static final ElRailingBlock RAILING = new ElRailingBlock(metal());
    public static final ElWallBlock WALL = new ElWallBlock(metal());
    public static final ElWallBlock WALL_GLASS = new com.stationannouncer.block.ElStackWallBlock(glass());
    public static final ElWallBlock WALL_MESH = new com.stationannouncer.block.ElStackWallBlock(metal());
    public static final ElWallBlock WALL_STEEL = new ElWallBlock(metal());
    public static final ElWallBlock WALL_DOORWAY = new ElWallDoorwayBlock(metal());
    public static final ElWallBlock WALL_ART_GLASS = new ElWallBlock(glass());
    public static final ElLampPoleBlock LAMP_POLE = new ElLampPoleBlock(metal(),
            Block.createCuboidShape(6.8, 0.0, 0.0, 9.2, 16.0, 2.4));
    public static final FacingDecorBlock LAMP_HEAD = new FacingDecorBlock(
            AbstractBlock.Settings.create().strength(1.0f).sounds(BlockSoundGroup.METAL).nonOpaque().luminance(state -> 14),
            Block.createCuboidShape(4.5, 0.0, 0.0, 11.5, 10.5, 16.0));
    public static final ElRoofLightBlock ROOF_LIGHT = new ElRoofLightBlock(
            AbstractBlock.Settings.create().strength(1.0f).sounds(BlockSoundGroup.METAL).nonOpaque().luminance(state -> 15),
            Block.createCuboidShape(6.0, 11.0, 0.0, 10.0, 16.0, 16.0));
    // stairs
    public static final ElStairSideBlock STAIR_RAILING = new ElStairSideBlock(metal()).inCell(SubwayStairBlock.InSide.ESI_RAILING);
    public static final ElStairSideBlock STAIR_WALL = new ElStairSideBlock(metal(), true).inCell(SubwayStairBlock.InSide.ESI_WALL);
    public static final ElStairSideBlock STAIR_WALL_GLASS = new ElStairSideBlock(glass(), true).inCell(SubwayStairBlock.InSide.ESI_WALL);
    public static final ElStairSideBlock STAIR_OPEN = new ElStairSideBlock(metal()).inCell(SubwayStairBlock.InSide.ESI_STRINGER);
    public static final ElStairUpperBlock STAIR_UPPER = new ElStairUpperBlock(metal()).inCell(SubwayStairBlock.InSide.ESI_WALL);
    public static final ElStairRoofBlock STAIR_ROOF = new ElStairRoofBlock(metal());
    public static final ElLandingRoofBlock LANDING_ROOF = new ElLandingRoofBlock(metal());
    public static final DecorBlock STAIR_LANDING = new DecorBlock(metal(), Block.createCuboidShape(0.0, 11.0, 0.0, 16.0, 16.0, 16.0));
    // structure
    public static final ColumnBlock STREET_COLUMN = new ColumnBlock(structure(), Block.createCuboidShape(3.0, 0.0, 3.0, 13.0, 16.0, 13.0));
    public static final ColumnBlock STREET_COLUMN_LATTICE = new ColumnBlock(structure(), Block.createCuboidShape(3.0, 0.0, 3.0, 13.0, 16.0, 13.0));
    public static final ElGirderBlock GIRDER_PLATE = new ElGirderBlock(structure());
    public static final ElDeckBlock TRACK_DECK = new ElDeckBlock(structure());
    public static final ElDeckBlock PLATE_DECK = new ElDeckBlock(structure());
    // mezzanine
    public static final ElMezzanineFloorBlock MEZZANINE_FLOOR = new ElMezzanineFloorBlock(
            AbstractBlock.Settings.create().strength(3.0f, 6.0f).sounds(BlockSoundGroup.STONE).nonOpaque());
    public static final ElCeilingBlock CEILING = new ElCeilingBlock(metal());
    public static final ElCeilingBlock CEILING_LIGHT = new ElCeilingBlock(metal().luminance(state -> 15));

    public static final ItemGroup MODERN = FabricItemGroup.builder()
            .icon(() -> new ItemStack(WALL_GLASS))
            .displayName(Text.translatable("itemGroup.station_announcer.modern"))
            .entries((context, entries) -> ENTRIES.forEach(entries::add))
            .build();

    public static void register() {
        add("esi_roof", ROOF, null);
        add("esi_post", POST, null);
        add("esi_railing", RAILING, new EdgeRunItem(RAILING, new Item.Settings()));
        add("esi_wall", WALL, new EdgeRunItem(WALL, new Item.Settings()));
        add("esi_wall_glass", WALL_GLASS, new EdgeRunItem(WALL_GLASS, new Item.Settings()));
        add("esi_wall_mesh", WALL_MESH, new EdgeRunItem(WALL_MESH, new Item.Settings()));
        add("esi_wall_steel", WALL_STEEL, new EdgeRunItem(WALL_STEEL, new Item.Settings()));
        add("esi_wall_doorway", WALL_DOORWAY, new EdgeRunItem(WALL_DOORWAY, new Item.Settings()));
        add("esi_wall_art_glass", WALL_ART_GLASS, new EdgeRunItem(WALL_ART_GLASS, new Item.Settings()));
        add("esi_platform_lamp", LAMP_POLE, null);
        add("esi_platform_lamp_head", LAMP_HEAD, null);
        add("esi_roof_light", ROOF_LIGHT, null);
        add("esi_stair_railing", STAIR_RAILING, new ElStairSideItem(STAIR_RAILING, new Item.Settings()));
        add("esi_stair_wall", STAIR_WALL, new ElStairSideItem(STAIR_WALL, new Item.Settings()));
        add("esi_stair_wall_glass", STAIR_WALL_GLASS, new ElStairSideItem(STAIR_WALL_GLASS, new Item.Settings()));
        add("esi_stair_open", STAIR_OPEN, new ElStairSideItem(STAIR_OPEN, new Item.Settings()));
        add("esi_stair_upper", STAIR_UPPER, new ElStairUpperItem(STAIR_UPPER, new Item.Settings()));
        add("esi_stair_roof", STAIR_ROOF, null);
        add("esi_landing_roof", LANDING_ROOF, null);
        add("esi_stair_landing", STAIR_LANDING, null);
        add("esi_street_column", STREET_COLUMN, null);
        add("esi_street_column_lattice", STREET_COLUMN_LATTICE, null);
        add("esi_girder_plate", GIRDER_PLATE, null);
        add("esi_track_deck", TRACK_DECK, null);
        add("esi_plate_deck", PLATE_DECK, null);
        add("esi_mezzanine_floor", MEZZANINE_FLOOR, null);
        add("esi_ceiling", CEILING, null);
        add("esi_ceiling_light", CEILING_LIGHT, null);
        // girders frame into ESI columns exactly like classic ones
        ElGirderBlock.COLUMNS.add(STREET_COLUMN);
        ElGirderBlock.COLUMNS.add(STREET_COLUMN_LATTICE);
        Registry.register(Registries.ITEM_GROUP, StationAnnouncer.id("modern"), MODERN);
    }

    private static void add(String name, Block block, BlockItem item) {
        Registry.register(Registries.BLOCK, StationAnnouncer.id(name), block);
        BlockItem it = item != null ? item : new BlockItem(block, new Item.Settings());
        Registry.register(Registries.ITEM, StationAnnouncer.id(name), it);
        ENTRIES.add(it);
        BLOCKS.add(block);
    }
}
